### PR TITLE
Response analysis for pilot and current Cycle 1 data

### PR DESCRIPTION
**Pull request by mhoover**
This PR provides the response funnel analysis for both the pilot and Cycle 1 experiments. The pilot work should be considered legacy code -- good to keep around, but not something that likely needs to be run again as the data, systems used, and structure have all changed since originally run. 

The `response_analysis.r` script is the one that is relevant. It takes in a variety of data sources and puts together one dataset with the number of people that completed NGS2 empanelment. Input files include:
* Empanelment data; this is collected from Qualtrics
* Panel demographics; this is collected internally from the Gallup Panel team
* Experiment signup times; this is from an internal Gallup process
* Breadboard data; this comes from processed Breadboard (experiment) files

### CODE REVIEW

**Comment by mhoover** [comment]
@pablo-diego-rosell Any thoughts on this? It's been up here for a while...

**Comment by C-Pablo-Diego-Rosell** [comment]
Thanks for the reminder, it’s on my to do list, but with a low priority, at least until November.

**Comment by mhoover** [comment]
Understood.

**Comment by mhoover** [comment]
Per conversation with @pablo-diego-rosell merging this. If we need to touch up during Cycle 2, we can open a new PR.

**Pull request merged**
