### PR TITLE
Set up processing of participant payments

### PR DESCRIPTION
**Pull request by mhoover**
This PR provides a wrapper around the [PayPal Python SDK](https://github.com/paypal/PayPal-Python-SDK) to process and send payouts to participants in NGS2 experiments using the [PayPal APIs](https://developer.paypal.com). It includes robust logging, tests, and virtual environment use to ensure use of up-to-date security requirements.

### CODE REVIEW

**Comment by mhoover** [comment]
Actually, I'm wondering if we should open a different repo for the various API work I've been doing (this is just the start; there is this work on PayPal's APIs, but also Qualtrics and Twilio (possibly)). Keep the `NGS2` repo for analytics only? Though @uduwage and @pablo-diego-rosell?

**Comment by C-Pablo-Diego-Rosell** [comment]
Makes sense!

**Comment by mhoover** [comment]
Cool, thanks Pablo. Let's see what Anu says as well and let's hold off on review/merging until we get this issues settled.

**Comment by mhoover** [comment]
Closing as PR opened up at https://github.com/gallup/NGS2-apis/pull/1 instead.

**Pull request closed without merging**
